config/routes.rb
Sld::Application.routes.draw do
  resources :signs

  resources :sign_languages

  resources :categories

  resources :words

  resources :meanings

end

app/models/sign_language.rb
class SignLanguage < ActiveRecord::Base
  validates :acronym,  :presence => true, :uniqueness => true
  validates :name, :presence => true
  has_many :signs
  has_many :meanings, :through => :signs
  default_scope order('sign_language.acronym')
end

app/controllers/sign_languages_controller.rb
class SignLanguagesController < ApplicationController
  # GET /sign_languages
  # GET /sign_languages.xml
  def index
    @sign_languages = SignLanguage.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sign_languages }
    end
  end

  # GET /sign_languages/1
  # GET /sign_languages/1.xml
  def show
    @sign_language = SignLanguage.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sign_language }
    end
  end

  # GET /sign_languages/new
  # GET /sign_languages/new.xml
  def new
    @sign_language = SignLanguage.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sign_language }
    end
  end

  # GET /sign_languages/1/edit
  def edit
    @sign_language = SignLanguage.find(params[:id])
  end

  # POST /sign_languages
  # POST /sign_languages.xml
  def create
    @sign_language = SignLanguage.new(params[:sign_language])

    respond_to do |format|
      if @sign_language.save
        format.html { redirect_to(@sign_language, :notice => 'Sign language was successfully created.') }
        format.xml  { render :xml => @sign_language, :status => :created, :location => @sign_language }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sign_language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sign_languages/1
  # PUT /sign_languages/1.xml
  def update
    @sign_language = SignLanguage.find(params[:id])

    respond_to do |format|
      if @sign_language.update_attributes(params[:sign_language])
        format.html { redirect_to(@sign_language, :notice => 'Sign language was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sign_language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_languages/1
  # DELETE /sign_languages/1.xml
  def destroy
    @sign_language = SignLanguage.find(params[:id])
    @sign_language.destroy

    respond_to do |format|
      format.html { redirect_to(sign_languages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sign_languages_helper.rb
module SignLanguagesHelper
end

app/views/sign_languages/_form.html.erb
<%= form_for(@sign_language) do |f| %>
  <% if @sign_language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_language.errors.count, "error") %> prohibited this sign_language from being saved:</h2>

      <ul>
      <% @sign_language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br />
    <%= f.text_field :acronym %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sign_languages/edit.html.erb
<h1>Editing sign_language</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_language %> |
<%= link_to 'Back', sign_languages_path %>

app/views/sign_languages/index.html.erb
<h1>Listing sign_languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Acronym</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sign_languages.each do |sign_language| %>
  <tr>
    <td><%= sign_language.name %></td>
    <td><%= sign_language.acronym %></td>
    <td><%= sign_language.description %></td>
    <td><%= link_to 'Show', sign_language %></td>
    <td><%= link_to 'Edit', edit_sign_language_path(sign_language) %></td>
    <td><%= link_to 'Destroy', sign_language, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sign language', new_sign_language_path %>

app/views/sign_languages/new.html.erb
<h1>New sign_language</h1>

<%= render 'form' %>

<%= link_to 'Back', sign_languages_path %>

app/views/sign_languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sign_language.name %>
</p>

<p>
  <b>Acronym:</b>
  <%= @sign_language.acronym %>
</p>

<p>
  <b>Description:</b>
  <%= @sign_language.description %>
</p>
<% @sign_language.meanings.each do |meaning| %>
  <tr>
    <td><%= meaning.word.name %>
    ( <%= meaning.category.name %> ) - 
    <%= meaning.description %>
	<%= meaning.signs %>
    <%= link_to 'Show', meaning %>
    <%= link_to 'Edit', edit_meaning_path(meaning) %></td>
  </tr>
<% end %>

<%= link_to 'Edit', edit_sign_language_path(@sign_language) %> |
<%= link_to 'Back', sign_languages_path %>