config/routes.rb
Sld::Application.routes.draw do
  resources :signs

  resources :sign_languages

  resources :categories

  resources :words

  resources :meanings

end

app/models/sign.rb
class Sign < ActiveRecord::Base
  belongs_to :signLanguage
  belongs_to :meaning
  #validates  :meaning, :uniqueness => {:scope => :signLanguage}
  has_one :word, :through => :meaning
  has_one :category, :through => :meaning
  def self.getLastFive(signLanguage_id)
    order("updated_at DESC").limit(5)
  end
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  # GET /signs
  # GET /signs.xml
  def index
    @signs = Sign.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @signs }
    end
  end

  # GET /signs/1
  # GET /signs/1.xml
  def show
    @sign = Sign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sign }
    end
  end

  # GET /signs/new
  # GET /signs/new.xml
  def new
    @sign = Sign.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sign }
    end
  end

  # GET /signs/1/edit
  def edit
    @sign = Sign.find(params[:id])
  end

  # POST /signs
  # POST /signs.xml
  def create
    @sign = Sign.new(params[:sign])

    respond_to do |format|
      if @sign.save
        format.html { redirect_to(@sign, :notice => 'Sign was successfully created.') }
        format.xml  { render :xml => @sign, :status => :created, :location => @sign }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /signs/1
  # PUT /signs/1.xml
  def update
    @sign = Sign.find(params[:id])

    respond_to do |format|
      if @sign.update_attributes(params[:sign])
        format.html { redirect_to(@sign, :notice => 'Sign was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /signs/1
  # DELETE /signs/1.xml
  def destroy
    @sign = Sign.find(params[:id])
    @sign.destroy

    respond_to do |format|
      format.html { redirect_to(signs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/views/signs/_form.html.erb
<%= form_for(@sign) do |f| %>
  <% if @sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
      <% @sign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :signLanguage %><br />
    <%= f.text_field :signLanguage %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br />
    <%= f.text_field :meaning%>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :gesturegram %><br />
    <%= f.text_area :gesturegram %>
  </div>
  <div class="field">
    <%= f.label :xmlDescription %><br />
    <%= f.text_area :xmlDescription %>
  </div>
  <div class="field">
    <%= f.label :renderedFile %><br />
    <%= f.text_field :renderedFile %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signs/edit.html.erb
<h1>Editing sign</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign %> |
<%= link_to 'Back', signs_path %>

app/views/signs/index.html.erb
<h1>Listing signs</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Gesturegram</th>
    <th>Xmldescription</th>
    <th>Renderedfile</th>
    <th>Signlanguage</th>
    <th>Meaning</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signs.each do |sign| %>
  <tr>
    <td><%= sign.description %></td>
    <td><%= sign.gesturegram %></td>
    <td><%= sign.xmlDescription %></td>
    <td><%= sign.renderedFile %></td>
    <td><%= sign.signLanguage %></td>
    <td><%= sign.meaning %></td>
    <td><%= link_to 'Show', sign %></td>
    <td><%= link_to 'Edit', edit_sign_path(sign) %></td>
    <td><%= link_to 'Destroy', sign, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sign', new_sign_path %>

app/views/signs/new.html.erb
<h1>New sign</h1>

<%= render 'form' %>

<%= link_to 'Back', signs_path %>

app/views/signs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @sign.description %>
</p>

<p>
  <b>Gesturegram:</b>
  <%= @sign.gesturegram %>
</p>

<p>
  <b>Xmldescription:</b>
  <%= @sign.xmlDescription %>
</p>

<p>
  <b>Renderedfile:</b>
  <%= @sign.renderedFile %>
</p>

<p>
  <b>Signlanguage:</b>
  <%= @sign.signLanguage.acronym %>
</p>
<p>
  <b>Word:</b>
  <%= @sign.word.name %> ( <%= @sign.category.name %> )-
</p>
<p>
  <b>Meaning:</b>
  <%= @sign.meaning.description %>
</p>



<%= link_to 'Edit', edit_sign_path(@sign) %> |
<%= link_to 'Back', signs_path %>