config/routes.rb
Sld::Application.routes.draw do
  resources :signs

  resources :sign_languages

  resources :categories

  resources :words

  resources :meanings

end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
  #validates  :word, :uniqueness => {:scope => :category}
  belongs_to :word
  belongs_to :category
  has_many   :signs
end

app/controllers/meanings_controller.rb
class MeaningsController < ApplicationController
  # GET /meanings
  # GET /meanings.xml
  def index
    @meanings = Meaning.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @meanings }
    end
  end

  # GET /meanings/1
  # GET /meanings/1.xml
  def show
    @meaning = Meaning.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meaning }
    end
  end

  # GET /meanings/new
  # GET /meanings/new.xml
  def new
    @meaning = Meaning.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meaning }
    end
  end

  # GET /meanings/1/edit
  def edit
    @meaning = Meaning.get(params[:id])
  end

  # POST /meanings
  # POST /meanings.xml
  def create
    @meaning = Meaning.new(params[:meaning])

    respond_to do |format|
      if @meaning.save
        format.html { redirect_to(@meaning, :notice => 'Meaning was successfully created.') }
        format.xml  { render :xml => @meaning, :status => :created, :location => @meaning }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meaning.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meanings/1
  # PUT /meanings/1.xml
  def update
    @meaning = Meaning.get(params[:id])

    respond_to do |format|
      if @meaning.update_attributes(params[:meaning])
        format.html { redirect_to(@meaning, :notice => 'Meaning was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meaning.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meanings/1
  # DELETE /meanings/1.xml
  def destroy
    @meaning = Meaning.get(params[:id])
    @meaning.destroy

    respond_to do |format|
      format.html { redirect_to(meanings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/meanings_helper.rb
module MeaningsHelper
end

app/views/meanings/_form.html.erb
<%= form_for(@meaning) do |f| %>
  <% if @meaning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meaning.errors.count, "error") %> prohibited this meaning from being saved:</h2>

      <ul>
      <% @meaning.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meanings/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @meaning %> |
<%= link_to 'Back', meanings_path %>

app/views/meanings/index.html.erb
<h1>Listing meanings</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Category</th>
	<th>description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meanings.each do |meaning| %>
  <tr>
    <td><%= meaning.word.name %></td>
	<td><%= meaning.category.name %></td>
	<td><%= meaning.description %></td>
    <td><%= link_to 'Show', meaning %></td>
    <td><%= link_to 'Edit', edit_meaning_path(meaning) %></td>
    <td><%= link_to 'Destroy', meaning, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meaning', new_meaning_path %>

app/views/meanings/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', meanings_path %>

app/views/meanings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @meaning.word.name %>
  (<%= @meaning.category.name %>)- 
  <%= @meaning.description %>
  <% @meaning.signs.each do |sign| %>
  <b>Sign: <%= link_to sign.signLanguage.acronym, sign.signLanguage %></b>
  <%= sign.description %>
    <%= sign.gesturegram %>
    <%= sign.description %>
	<%= sign.signs %>
    <%= link_to 'Show', sign %>
    <%= link_to 'Edit', edit_sign_path(sign) %>
  <% end %>
</p>


<%= link_to 'Edit', edit_meaning_path(@meaning) %> |
<%= link_to 'Back', meanings_path %>